export const CHANGE_NAME_SEARCH_FIELD = 'CHANGE_NAME_SEARCH_FIELD';
export const CHANGE_SOW_SEARCH_FIELD = 'CHANGE_SOW_SEARCH_FIELD';
export const CHANGE_HARVEST_SEARCH_FIELD = 'CHANGE_HARVEST_SEARCH_FIELD';